// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufgtbltzgpqfvuupiujg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmZ3RibHR6Z3BxZnZ1dXBpdWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzA5MTYsImV4cCI6MjA2OTcwNjkxNn0.m4Umtbc8cDH-11oIh5nwxR_O2lemOMLaxK8Ga85YnDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});